services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    tty: true
    stdin_open: true
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"

  db:
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  dbdata:
